### ISSUE TITLE
请尽快提交关于20190728小组作业的个人意见

### ISSUE THREAD

**Issue by jezecheng** [jezecheng/fudan_mba_2019_8_g45#1]
# update 已merge各位上传同学建议至
[readme.md](https://github.com/jezecheng/fudan_mba_2019_8_g45/tree/master/01_%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88)

----

- [构建建议 -- 忻莉元同学](https://github.com/jezecheng/fudan_mba_2019_8_g45/blob/master/01_%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88/%E6%A9%998%E7%8F%AD%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E4%B9%8B%E6%B5%85%E8%A7%81-%E5%BF%BB%E8%8E%89%E5%85%83.MD) 支持在线预览
- [构建建议 -- 程华同学](https://github.com/jezecheng/fudan_mba_2019_8_g45/blob/master/01_%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88/%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88_%E7%A8%8B%E5%8D%8E.MD) 支持在线预览
- [构建建议 -- 程童同学](https://github.com/jezecheng/fudan_mba_2019_8_g45/blob/master/01_%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88/%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88_%E7%A8%8B%E7%AB%A5.MD) 支持在线预览
- [构建建议 -- 柳婧同学](https://github.com/jezecheng/fudan_mba_2019_8_g45/blob/master/01_%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88/%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E5%BB%BA%E8%AE%AE_%E6%9F%B3%E5%A9%A7.MD) 支持在线预览
- [组织建议PPT -- 侯艳婷同学](https://github.com/jezecheng/fudan_mba_2019_8_g45/blob/master/01_%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88/PPT_%E5%80%99%E8%89%B3%E5%90%AC.pdf) 
- [组织建议PPT -- 顾雯静同学](https://github.com/jezecheng/fudan_mba_2019_8_g45/blob/master/01_%E7%8F%AD%E7%BA%A7%E7%BB%84%E7%BB%87%E5%BD%A2%E6%80%81%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88/%E9%A1%BE%E9%9B%AF%E9%9D%99.pdf)
- 组织架构建议 -- 龚元同学
![org-chart](https://user-images.githubusercontent.com/23181126/61879999-a433ff80-af26-11e9-985e-01e42340cee1.png)

**Comment by jezecheng** [comment]
![Alt Text](https://baike.baidu.com/pic/orange/38553/0/eaf81a4c510fd9f9d0bc59c72b2dd42a2934a4f0?fr=lemma&ct=single)

**Comment by VeraChenghua** [comment]
大家好，我是程华。谢谢程童同学的组织~看了王朝阳同学的作业，我有点迷惑了，我认为作业要求是：阐述个人对班级组织形态构建方案的简介、自己可以提供的资源以及所需的支持。好像不是要做Ori发的那份材料吧。。。。我根据自己的理解写的作业请见附件，请大家指点~
[班级组织形态构建方案_程华.docx](https://github.com/jezecheng/fudan_mba_2019_8_g45/files/3429848/_.docx)

**Comment by VeraChenghua** [comment]
诶，为什么上面有删除线。。。

**Comment by VeraChenghua** [comment]
能看到吗

**Comment by StaceyXin** [comment]
大家好~我是忻莉元~ 感谢程童同学的组织，给我们搭建一个那么好沟通平台！可惜我不争气，搞了好久才“着陆”Git...现在找到组织了还是非常滴开心！
言归正传，就班级组织形态的构建，这是我个人的一些浅见，欢迎大家提出意见，一起讨论！
[橙8班班级组织形态构建之浅见-忻莉元.docx](https://github.com/jezecheng/fudan_mba_2019_8_g45/files/3431813/8.-.docx)

@VeraChenghua 你的方案好详细，喜欢！我们想法有些是很相似，并且我在你“可提供资源”的基础上想到了，以后我可以赞助一些3M产品来配合班级活动，比如口罩，运动护具，医疗消毒产品，文具等等...给班级同学带来些便利和乐趣~~~

**Comment by jezecheng** [comment]
# On Behalf of 龚元同学
![org-chart](https://user-images.githubusercontent.com/23181126/61879999-a433ff80-af26-11e9-985e-01e42340cee1.png)

**Comment by StaceyXin** [comment]
@jezecheng 程同学！！我现在体会到你这个工具的好用之处了，优秀优秀！！ 🍡

**Comment by michelle355** [comment]
大家好，我是侯艳婷Michelle. 作业晚来了，第一稿方案不够完善，希望多和同学们的思想做个碰撞~由于是策划出身，后续PPT可以我来~
[班级组织形态构建方案.pdf](https://github.com/jezecheng/fudan_mba_2019_8_g45/files/3434021/default.pdf)

**Comment by VeraChenghua** [comment]
@ michelle355  PPT好棒！同意以项目驱动而不是以职能驱动的观点

**Comment by jezecheng** [comment]
repost

**Comment by Guo-wenjing** [comment]
不好意思回晚拉，有感于大家的分享，好多点子，受到启发（晚有晚的好^.^），也找了些资料做参考，赶在要求的周六前完成拉，幸不辱命，哈哈哈
[组织形态构建-郭雯静0726.pdf](https://github.com/jezecheng/fudan_mba_2019_8_g45/files/3436012/-.0726.pdf)
